import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { db } from '@/db';
import { changelogEntries, type NewChangelogEntry } from '@/db/schema';
import { desc, eq, and } from 'drizzle-orm';

/**
 * GET /api/admin/changelog
 * Fetch all changelog entries, ordered by date descending
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type');
    const projectId = searchParams.get('projectId');
    const limit = parseInt(searchParams.get('limit') || '50', 10);

    const conditions = [];
    if (projectId) conditions.push(eq(changelogEntries.projectId, projectId));
    if (type && type !== 'all') {
      conditions.push(eq(changelogEntries.type, type as typeof changelogEntries.type.enumValues[number]));
    }

    const where = conditions.length === 0
      ? undefined
      : conditions.length === 1
        ? conditions[0]
        : and(...conditions);

    const entries = await db
      .select()
      .from(changelogEntries)
      .where(where)
      .orderBy(desc(changelogEntries.createdAt))
      .limit(limit);

    return NextResponse.json({ entries });
  } catch (error) {
    console.error('Error fetching changelog:', error);
    return NextResponse.json(
      { error: 'Failed to fetch changelog entries' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/admin/changelog
 * Create a new changelog entry
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    const newEntry: NewChangelogEntry = {
      type: body.type,
      title: body.title,
      description: body.description || null,
      phaseId: body.phaseId || null,
      phaseName: body.phaseName || null,
      deliverableName: body.deliverableName || null,
      previousStatus: body.previousStatus || null,
      newStatus: body.newStatus || null,
      isAutoGenerated: body.isAutoGenerated || false,
      isPinned: body.isPinned || false,
      projectId: body.projectId || null,
    };

    const [entry] = await db
      .insert(changelogEntries)
      .values(newEntry)
      .returning();

    return NextResponse.json({ entry }, { status: 201 });
  } catch (error) {
    console.error('Error creating changelog entry:', error);
    return NextResponse.json(
      { error: 'Failed to create changelog entry' },
      { status: 500 }
    );
  }
}
